### ISSUE TITLE
Introduce mentor and mentee objects and rewrite code to use them

### ISSUE THREAD

**Issue by sectorsize512** [sectorsize512/mentorship#2]
Currently the code relies on tuples a lot. It is not a good coding practice for many reasons. Introducing `mentee` and `mentor` objects will make the code easier to write and maintain.

**Comment by tarver52** [comment]
check please

**Comment by sectorsize512** [comment]
Looks good to  me , TY. I have two minor comments to discuss during the call:

1. Function definition in the middle of the global code
2. `None` used as an error (abnormal status) indicator:
